/*
  Copyright (c) 2024-present, Trail of Bits, Inc.
  All rights reserved.

  This source code is licensed in accordance with the terms specified in
  the LICENSE file found in the root directory of this source tree.
*/

#pragma once

#include <QString>

#include <gap/core/generator.hpp>
#include <memory>
#include <multiplier/Frontend/File.h>

#include "IInfoGeneratorItem.h"

namespace mx::gui {

class IInfoGenerator;

using IInfoGeneratorPtr = std::shared_ptr<IInfoGenerator>;

//! Data generator for an entity tree. The data generator can be arbitrarily
//! slow at generating its data.
class IInfoGenerator : public std::enable_shared_from_this<IInfoGenerator> {
 public:
  virtual ~IInfoGenerator(void);

  // The category name of info generated by this generator.
  //
  // NOTE(pag): This must be non-blocking.
  virtual QString Category(void) const = 0;

  // Generate the information items for this category.
  //
  // NOTE(pag): These are `shared_ptr`s so that implementations have the
  //            flexibility of having tree items extend the lifetime of
  //            tree generator (`self`) itself via aliasing `std::shared_ptr`.
  //
  // NOTE(pag): This is allowed to block.
  virtual gap::generator<IInfoGeneratorItemPtr> Items(
      IInfoGeneratorPtr self, FileLocationCache file_location_cache) = 0;
};

}  // namespace mx::gui

Q_DECLARE_INTERFACE(mx::gui::IInfoGenerator,
                    "com.trailofbits.interface.IInfoGenerator")
