#
# Copyright (c) 2023-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Build

on:
  schedule:
    - cron: '00 21 * * *'

  pull_request:
    branches:
      - '*'

  push:
    branches:
      - 'main'

concurrency:
  group: main-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  macos:
    # Disable for now, we can no longer build the multiplier library
    # like this
    if: false

    strategy:
      matrix:
        build_type: [Release]

    uses: ./.github/workflows/posix.yml
    secrets: inherit

    with:
      platform: macos-12
      build_type: ${{ matrix.build_type }}
      multiplier_release: b3b1027
      python_version: 3.11
      llvm_version: 17

  linux:
    strategy:
      matrix:
        build_type: [Release]

    uses: ./.github/workflows/posix.yml
    secrets: inherit

    with:
      platform: ubuntu-22.04
      build_type: ${{ matrix.build_type }}
      multiplier_release: b3b1027
      python_version: 3.11
      llvm_version: 17
