#
# Copyright (c) 2023-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Build

on:
  schedule:
    - cron: '00 21 * * *'

  pull_request:
    branches:
      - '*'

  push:
    branches:
      - 'next'

concurrency:
  group: next-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        build_type: [Release]

    uses: ./.github/workflows/posix.yml
    secrets: inherit

    with:
      platform: macos-12
      build_type: ${{ matrix.build_type }}
      cxx_common_tag: v0.4.0

  linux:
    strategy:
      matrix:
        build_type: [Release]

    uses: ./.github/workflows/posix.yml
    secrets: inherit

    with:
      platform: ubuntu-22.04
      build_type: ${{ matrix.build_type }}
      cxx_common_tag: v0.4.0
