#
# Copyright (c) 2023-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Posix

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

      build_type:
        required: true
        type: string

      multiplier_release:
        required: true
        type: string

      python_version:
        required: true
        type: string

      llvm_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    env:
      CACHE_KEY: platform-${{ inputs.platform }}_type-${{ inputs.build_type }}-${{ inputs.multiplier_release }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize the submodules
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.MX_MULTIPLIER_DEPLOY_KEY }}'

          git submodule update --init --recursive libraries/doctest/src
          git submodule update --init --recursive libraries/phantomstyle/src
          git submodule update --init --recursive libraries/xxhash/src
          git submodule update --init --recursive libraries/qt-advanced-docking-system/src
          git submodule update --init libraries/vendored/multiplier

      - name: Set the CCACHE_DIR environment variable
        run: |
          echo "CCACHE_DIR=${{ github.workspace }}/ccache" >> $GITHUB_ENV

      - name: Update the ccache cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache_${{ env.CACHE_KEY }}-${{ github.sha }}
          restore-keys: ccache_${{ env.CACHE_KEY }}

      - name: Create the ccache folder
        run: |
          mkdir -p \
            "${CCACHE_DIR}"

      - name: Install Python
        uses: trail-of-forks/setup-python@main
        with:
          python-version: "${{ inputs.python_version }}-dev"

      - name: Install Clang and LLVM
        uses: trail-of-forks/install-llvm-action@master
        with:
          version: "${{ inputs.llvm_version }}.0"

      - name: Install system dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            ccache \
            cmake \
            flex \
            bison \
            qt6-base-dev \
            libqt6core5compat6-dev \
            libgl1-mesa-dev \
            libglvnd-dev \
            cbindgen \
            gh

      - name: Download multiplier
        env:
          GITHUB_TOKEN: ${{ secrets.MULTIPLIER_TOKEN }}
        run: |
          folder_name="multiplier-${{ inputs.multiplier_release }}"
          archive_name="${folder_name}.tar.xz"
          gh release download ${{ inputs.multiplier_release }} --repo trailofbits/multiplier

          mkdir "${folder_name}"
          tar -xf "${archive_name}" --directory "${folder_name}"
          rm "${archive_name}"

          echo "MULTIPLIER_INSTALL_DIRECTORY=$(pwd)/${folder_name}" >> $GITHUB_ENV

      - name: Setup the build folders for the vendored libraries
        run: |
          mkdir qt_multiplier_install
          echo "QT_MULTIPLIER_INSTALL_DIRECTORY=$(pwd)/qt_multiplier_install" >> $GITHUB_ENV

      - name: Determine job count
        id: job_count
        run: |
          echo "VALUE=$(nproc)" >> $GITHUB_OUTPUT

      - name: Build qt-multiplier
        run: |
          bash ./scripts/build_qtsdk.sh --redist

          cmake \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            -DCMAKE_C_COMPILER="${{ env.LLVM_PATH }}/bin/clang" \
            -DCMAKE_CXX_COMPILER="${{ env.LLVM_PATH }}/bin/clang++" \
            -DMXQT_ENABLE_TESTS=true \
            -DMXQT_MULTIPLIER_VERSION=${{ inputs.multiplier_release }} \
            -Dmultiplier_DIR="${MULTIPLIER_INSTALL_DIRECTORY}/lib/cmake/multiplier" \
            -Dgap_DIR="${MULTIPLIER_INSTALL_DIRECTORY}/lib/cmake/gap" \
            -DQt6_DIR=${{ github.workspace }}/qt5-install/usr/local/Qt-6.7.0/lib/cmake/Qt6 \
            -DQt6Gui_DIR=${{ github.workspace }}/qt5-install/usr/local/Qt-6.7.0/lib/cmake/Qt6Gui \
            -S . \
            -B build_qtmultiplier

          cmake \
            --build build_qtmultiplier \
            -j ${{ steps.job_count.outputs.VALUE }}

          export DESTDIR="${QT_MULTIPLIER_INSTALL_DIRECTORY}"

          cmake \
            --build build_qtmultiplier \
            --target install

      - name: Run the qt-multiplier tests
        if: false
        run: |
          cmake \
            --build build_qtmultiplier \
            --target test

      - name: Create the DEB package
        id: deb_package
        run: |
          cmake \
            -S package \
            -B package-build \
            -DQT_MULTIPLIER_DATA_PATH="${QT_MULTIPLIER_INSTALL_DIRECTORY}" \
            -DMULTIPLIER_DATA_PATH="${MULTIPLIER_INSTALL_DIRECTORY}" \
            -DCPACK_GENERATOR=DEB

          cmake \
            --build package-build \
            --target package

          rel_package_path="$(ls package-build/*.deb)"
          package_name="$(basename ${rel_package_path})"

          echo "PATH=${rel_package_path}" >> $GITHUB_OUTPUT
          echo "NAME=${package_name}" >> $GITHUB_OUTPUT

      - name: Upload the DEB package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.deb_package.outputs.NAME }}
          path: ${{ steps.deb_package.outputs.PATH }}
