#
# Copyright (c) 2023-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Posix

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

      build_type:
        required: true
        type: string

      multiplier_release:
        required: true
        type: string

      python_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    env:
      CACHE_KEY: platform-${{ inputs.platform }}_type-${{ inputs.build_type }}-${{ inputs.multiplier_release }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize the submodules
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.MX_MULTIPLIER_DEPLOY_KEY }}'

          git submodule update --init --recursive libraries/doctest/src
          git submodule update --init --recursive libraries/phantomstyle/src
          git submodule update --init --recursive libraries/xxhash/src

      - name: Set the CCACHE_DIR environment variable
        run: |
          echo "CCACHE_DIR=${{ github.workspace }}/ccache" >> $GITHUB_ENV

      - name: Update the ccache cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache_${{ env.CACHE_KEY }}-${{ github.sha }}
          restore-keys: ccache_${{ env.CACHE_KEY }}

      - name: Create the ccache folder
        run: |
          mkdir -p \
            "${CCACHE_DIR}"

      - name: Install system dependencies
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sudo chown -R $(whoami) $(brew --prefix)/*

            brew install \
              ccache \
              cmake \
              flex \
              bison \
              qt@6 \
              python@${{ inputs.python_version }} \
              curl

            brew unlink qt@6
            brew link qt@6

          else
            sudo apt update

            sudo apt install -y \
              clang-17 \
              clang++-17 \
              ccache \
              cmake \
              flex \
              bison \
              qt6-base-dev \
              libqt6core5compat6-dev \
              libgl1-mesa-dev \
              libglvnd-dev \
              python${{ inputs.python_version }} \
              python${{ inputs.python_version }}-dev \
              cbindgen \
              gh
          fi

      - name: Install multiplier
        env:
          GITHUB_TOKEN: ${{ secrets.MULTIPLIER_TOKEN }}
        run: |
          folder_name="multiplier-${{ inputs.multiplier_release }}"
          archive_name="${folder_name}.tar.xz"
          gh release download ${{ inputs.multiplier_release }} --repo trailofbits/multiplier
          mkdir "${folder_name}"
          tar -xf "${archive_name}" --directory "${folder_name}"
          rm "${archive_name}"
          echo "MULTIPLIER_INSTALL_DIRECTORY=$(pwd)/${folder_name}" >> $GITHUB_ENV

      - name: Setup the build folders for the vendored libraries
        run: |
          mkdir build_vendored
          mkdir qt_multiplier_install
          echo "QT_MULTIPLIER_INSTALL_DIRECTORY=$(pwd)/qt_multiplier_install" >> $GITHUB_ENV

      - name: Determine job count
        id: job_count
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            echo "VALUE=$(sysctl -n hw.ncpu)" >> $GITHUB_OUTPUT
          else
            echo "VALUE=$(nproc)" >> $GITHUB_OUTPUT
          fi

      - name: Build qt-multiplier
        run: |
          cmake \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            -DCMAKE_C_COMPILER=$(which clang-17) \
            -DCMAKE_CXX_COMPILER=$(which clang++-17) \
            -DMXQT_ENABLE_TESTS=true \
            -Dmultiplier_DIR="${MULTIPLIER_INSTALL_DIRECTORY}/lib/cmake/multiplier" \
            -Dgap_DIR="${MULTIPLIER_INSTALL_DIRECTORY}/lib/cmake/gap" \
            -S . \
            -B build_qtmultiplier

          cmake \
            --build build_qtmultiplier \
            -j ${{ steps.job_count.outputs.VALUE }}

          export DESTDIR="${QT_MULTIPLIER_INSTALL_DIRECTORY}"

          cmake \
            --build build_qtmultiplier \
            --target install

      - name: Run the qt-multiplier tests
        run: |
          cmake \
            --build build_qtmultiplier \
            --target test

      - name: Create the DMG package
        if: inputs.platform == 'macos-12'
        id: dmg_package
        run: |
          cmake \
            -S package \
            -B package-build \
            -DQT_MULTIPLIER_DATA_PATH="${QT_MULTIPLIER_INSTALL_DIRECTORY}" \
            -DMULTIPLIER_DATA_PATH="${MULTIPLIER_INSTALL_DIRECTORY}" \
            -DCPACK_GENERATOR=DragNDrop

          cmake \
            --build package-build \
            --target package

          rel_package_path="$(ls package-build/*.dmg)"
          package_name="$(basename ${rel_package_path})"

          echo "PATH=${rel_package_path}" >> $GITHUB_OUTPUT
          echo "NAME=${package_name}" >> $GITHUB_OUTPUT

      - name: Upload the DMG package
        if: inputs.platform == 'macos-12'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.dmg_package.outputs.NAME }}
          path: ${{ steps.dmg_package.outputs.PATH }}

      - name: Create the DEB package
        if: inputs.platform == 'ubuntu-22.04'
        id: deb_package
        run: |
          cmake \
            -S package \
            -B package-build \
            -DQT_MULTIPLIER_DATA_PATH="${QT_MULTIPLIER_INSTALL_DIRECTORY}" \
            -DMULTIPLIER_DATA_PATH="${MULTIPLIER_INSTALL_DIRECTORY}" \
            -DCPACK_GENERATOR=DEB

          cmake \
            --build package-build \
            --target package

          rel_package_path="$(ls package-build/*.deb)"
          package_name="$(basename ${rel_package_path})"

          echo "PATH=${rel_package_path}" >> $GITHUB_OUTPUT
          echo "NAME=${package_name}" >> $GITHUB_OUTPUT

      - name: Upload the DEB package
        if: inputs.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.deb_package.outputs.NAME }}
          path: ${{ steps.deb_package.outputs.PATH }}

      - name: Generate the sample database file
        run: |
          git clone "https://github.com/iovisor/ubpf"
          ( cd ubpf && git checkout -b sample_branch 0262957 )

          cmake \
            -S ubpf \
            -B build_ubpf \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=true

          "${MULTIPLIER_INSTALL_DIRECTORY}/bin/mx-index" \
            --target "build_ubpf/compile_commands.json" \
            --db /tmp/iovisor_ubpf.mx

          mv \
            /tmp/iovisor_ubpf.mx \
            .

      - name: Upload the sample database
        uses: actions/upload-artifact@v3
        with:
          name: iovisor_ubpf.mx
          path: iovisor_ubpf.mx
